# Generated by Django 4.0.1 on 2022-01-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
