# Generated by Django 4.0.1 on 2022-01-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_device_room_delete_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_identifier',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
