# Generated by Django 4.0.1 on 2022-01-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_device_device_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_identifier',
            field=models.CharField(max_length=200),
        ),
    ]
